services:
  web:
    build: .
    command: |
      sh -c "python manage.py migrate --settings=stripe_backend.settings &&
             python manage.py runserver 0.0.0.0:8000 --settings=stripe_backend.settings"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env